In [13]:
import numpy as np
from numpy import linalg as LA
import math
import scipy
import sys
!{sys.executable} -m pip install scipy

In [16]:
A = np.array([[1, 3, 2],[2,3,2], [4,4,4]])
V, E = LA.eig(A)
print(E)
print(V)

[[-0.40356127 -0.81563077 -0.1883618 ]
 [-0.45216387  0.13048019 -0.52544284]
 [-0.7954157   0.56366779  0.82971661]]
[ 8.30328514 -0.86208786  0.55880272]


TypeError: eig() got an unexpected keyword argument 'k'

In [23]:
# Calculate vector intensity using formula:
# |A| = sqrt(a1^2 + a2^2 + 3^2 +...+ an^2)
# where n = A.length
def intenzitet_vektora(a):
    suma = np.sum(a * a)
    return math.sqrt(suma)

# Find eigenvector for eigenvalue l = 1
# M - matrix
# l - lambda, eigenvalue
# x - eigenvector
# I - identity (unit) matrix
#
# Formula:
# Mx = lx
# (A - lI)x = 0
# |A-lI|x = 0
def svojstven_vekot_i_vrednost(M, l):
    # M must be n*n
    v, e = LA.eig(M)
    for i in range v.shape[0]:
        if v[i] == 1:
            return e[i]
        
    return []
    
    '''if not M.shape[0] == M.shape[1]:
        print('Nije kvadratna matrica!')
        return np.array([nan])
    
    I = np.identity(M.shape[0])
    I *= l
    
    A = M - I
    b = A[1,:]
    c = A[2,:]
    
    # choose x3
    x3 = 1
    
    # Calculate by fromula
    # b1x1 + b2a2 + b3x3 = 0
    # c1x1 + c2x2 + c3x3 = 0
    
    x2 = x3 * (b[0]*c[2]/c[1] - b[2]) / (b[1] - b[0]*c[1]/c[0])
    x1 = (x2 * -c[1] - c[2]*x3) / c[0]
    
    return np.array([x1, x2, x3])
    '''
def M2AngleAxis(M):
    p = svojstven_vekot_i_vrednost(M, 1)
    print(p)
    

def euler2A(fi, teta, ksi):
    cos_fi = math.cos(fi)
    sin_fi = math.sin(fi)
    
    RX = np.array([[1, 0,      0],
                   [0, cos_fi, -sin_fi],
                   [0, sin_fi,  cos_fi]])
    
    cos_teta = math.cos(teta)
    sin_teta = math.sin(teta)
    
    RY = np.array([[cos_teta, 0, sin_teta],
                  [0        , 1, 0],
                  [-sin_teta, 0, cos_teta]])
    
    cos_ksi = math.cos(ksi)
    sin_ksi = math.sin(ksi)
    RZ = np.array([[cos_ksi, -sin_ksi, 0],
                   [sin_ksi, cos_ksi,  0],
                   [0      , 0,        1]])
    
    A = np.dot(RZ,RY)
    A = np.dot(A,RX)
    return A

def a2Euler(A):
    if A[2,0] == -1:
        fi = 0
        teta = np.pi / 2
        ksi = -2*np.arctan2(A[1,1], -A[0,1])
    elif A[2,0] < 1:
        fi = np.arctan2( A[2,1], A[2,2])
        teta = np.arcsin(-A[2,0])
        ksi = np.arctan2(A[1,0], A[0,0])
    elif A[2,0] == 1:
        fi = 0
        teta = -np.pi / 2
        ksi = np.arctan2(A[0,1], -A[1,1])
    else:
        print("uneta losa matrica A")
        return (0,0,0)
    
    return (fi, teta, ksi)

def axisAngle(A):
    return 0

# done
def rodrigez(p, fi):
    fi_sin = np.sin(fi)
    fi_cos = np.cos(fi)
    
    p = p * 1/intenzitet_vektora(p)
    px = np.array([[0,    -p[2], p[1]], 
                   [p[2],  0,    -p[0]], 
                   [-p[1], p[0], 0]])
    
    return np.eye(3) + fi_sin * px + (1 - fi_cos) * px.dot(px)

def axisAngle2q(p, fi):
    d = math.sqrt(p[0]**2 + p[1]**2 + p[2]**2)
    p = p * 1/d
    p = np.sin(fi/2) * p
    
    return (p[0], p[1], p[2], np.cos(fi/2));

def q2AxisAngle(q): 
    a,b,c,d = q
    p = np.array([a,b,c])
    
    if d < 0:
        p *= -1
        d *= -1
    
    if d == 1:
        p = (1,0,0)
    else:
        s = math.sqrt(p[0]**2 + p[1]**2 + p[2]**2)
        p = p * 1/s
    
    return (p ,2 * np.arccos(d))

def normalizuj(q):
    suma = np.sum(q)
    
    return q * 1/suma
    


In [24]:
p2 = np.array([0,3,0])
alfa2 = np.pi/4

M = rodrigez(p2, alfa2)
print(M)
M2AngleAxis(M, 1)

[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]


TypeError: M2AngleAxis() takes 1 positional argument but 2 were given